name: Docker Pull and Push with Cache

on:
  push:
    branches:
      - main

#################################################################################################################################      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Docker layers
        id: cache-docker
        uses: actions/cache@v3
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}

      - name: Check cache hit
        id: check-cache-hit
        run: echo "::set-output name=cache-hit::$(echo ${{ steps.cache-docker.outputs.cache-hit }} | tr -d '\n')"

      - name: Docker pull
        if: steps.check-cache-hit.outputs.cache-hit != 'true'
        run: |
          docker pull mcr.microsoft.com/dotnet/aspnet:7.0
          docker pull mcr.microsoft.com/dotnet/sdk:7.0





